version: '3'

services:
  db:
    container_name: db
    image: pocketbase
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - '8090:8090'
    healthcheck: #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

  build:
    container_name: build
    image: build
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    ports:
      - '3000:3000'
